### ISSUE TITLE
UI never comes up

### ISSUE THREAD

**Issue by byjlw** [severian42/GraphRAG-Ollama-UI#3]
Ran through the instructions and the UI never starts up. 
Running the command to start the UI just gives me a cursor.
Also there is no settings.yaml to set the model and no definition of what the settings file should look like.
```
(.venv) jessewhite@MadMax GraphRAG-Ollama-UI % gradio app.py
\
> 
```

**Comment by byjlw** [comment]
actually found the settings file. Odd that it's in a directory named `test`
but still can't get the UI to launch. Tried going to `http://localhost:11434/v1` but it 404s

**Comment by severian42** [comment]
Hey! Sorry it took a minute to reply. Were you able to get the UI launch working? For the setting.yml, the reason why it's in a folder called 'ragtest' is mainly because I chose to keep the file structure the same as the Microsoft GraphRAG version. Under the hood of my UI, I am just launching the same command line arguments from their example. My version just cleans it up and makes it easier to work with all the files and outputs, but the overall implementation is the same as what you see in their repo. The Gradio UI can be launched with either 'gradio app.py' or 'python app.py' depending on your env setup. The UI URL should be localhost:7861 after executing the script. Let me know if you are still having issues
